name: test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: git config -l
      - run: echo "git config is - $(git config --get remote.origin.url)"
