name: test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          repository: hashicorp/packer
          ref: 36c2301781f69dd2f4aa38de28e2fdc7e8d5972a
      - run: git config -l
      - run: echo "git config is - $(git config --get remote.origin.url)"
